/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AclsV1AclPostDefaultResponseOneOf } from '../models/AclsV1AclPostDefaultResponseOneOf';
import { AclsV1AclPostDefaultResponseOneOf1 } from '../models/AclsV1AclPostDefaultResponseOneOf1';
import { HttpFile } from '../http/http';

export class AclsV1AclPostDefaultResponse {
    'errors'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AclsV1AclPostDefaultResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

