/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AnalyzeSchema {
    'force'?: boolean;
    'forceType'?: AnalyzeSchemaForceTypeEnum | null;
    'serviceName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "force",
            "baseName": "force",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "forceType",
            "baseName": "force_type",
            "type": "AnalyzeSchemaForceTypeEnum",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "service_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalyzeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AnalyzeSchemaForceTypeEnum {
    Overwrite = 'OVERWRITE',
    Append = 'APPEND'
}

