/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class AssetVersionSchema {
    'analyzeStatus'?: AssetVersionSchemaAnalyzeStatusEnum;
    'archiveStatus'?: AssetVersionSchemaArchiveStatusEnum;
    'createdByUser'?: string;
    'createdByUserInfo'?: User;
    'dateCreated'?: Date;
    'id'?: string;
    'isOnline'?: boolean;
    'status'?: AssetVersionSchemaStatusEnum;
    'transcribeStatus'?: AssetVersionSchemaTranscribeStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analyzeStatus",
            "baseName": "analyze_status",
            "type": "AssetVersionSchemaAnalyzeStatusEnum",
            "format": ""
        },
        {
            "name": "archiveStatus",
            "baseName": "archive_status",
            "type": "AssetVersionSchemaArchiveStatusEnum",
            "format": ""
        },
        {
            "name": "createdByUser",
            "baseName": "created_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdByUserInfo",
            "baseName": "created_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "isOnline",
            "baseName": "is_online",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AssetVersionSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "transcribeStatus",
            "baseName": "transcribe_status",
            "type": "AssetVersionSchemaTranscribeStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetVersionSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AssetVersionSchemaAnalyzeStatusEnum {
    NA = 'N/A',
    Requested = 'REQUESTED',
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    Done = 'DONE'
}
export enum AssetVersionSchemaArchiveStatusEnum {
    NotArchived = 'NOT_ARCHIVED',
    Archiving = 'ARCHIVING',
    FailedToArchive = 'FAILED_TO_ARCHIVE',
    Archived = 'ARCHIVED'
}
export enum AssetVersionSchemaStatusEnum {
    Active = 'ACTIVE',
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    Deleting = 'DELETING',
    Deleted = 'DELETED'
}
export enum AssetVersionSchemaTranscribeStatusEnum {
    NA = 'N/A',
    Requested = 'REQUESTED',
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    Done = 'DONE'
}

