/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetVersion } from '../models/AssetVersion';
import { RelationElastic } from '../models/RelationElastic';
import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class AssetElasticSchema {
    'analyzeStatus'?: AssetElasticSchemaAnalyzeStatusEnum;
    'archiveStatus'?: AssetElasticSchemaArchiveStatusEnum;
    'category'?: string | null;
    'commentsCount'?: number;
    'createdByUser'?: string;
    'createdByUserInfo'?: User;
    'customKeyframe'?: string | null;
    'customPoster'?: string | null;
    'dateCreated'?: Date;
    'dateDeleted'?: Date;
    'dateImported'?: Date;
    'dateModified'?: Date;
    'dateViewed'?: Date;
    'deletedByUser'?: string;
    'deletedByUserInfo'?: User;
    'durationMilliseconds'?: number;
    'externalId'?: string | null;
    'externalLink'?: string | null;
    'favoured'?: boolean;
    'files'?: Array<any>;
    'id'?: string;
    'inCollections'?: Array<string>;
    'isBlocked'?: boolean;
    'isOnline'?: boolean;
    'keyframes'?: Array<any>;
    'mediaType'?: string | null;
    'metadata'?: any;
    'objectType'?: string;
    'originalAssetId'?: string;
    'originalSegmentId'?: string;
    'originalVersionId'?: string;
    'position'?: number;
    'proxies'?: Array<any>;
    'relations'?: Array<RelationElastic>;
    'siteName'?: string | null;
    'status'?: AssetElasticSchemaStatusEnum;
    'timeEndMilliseconds'?: number;
    'timeStartMilliseconds'?: number;
    'title': string;
    'type'?: AssetElasticSchemaTypeEnum;
    'updatedByUser'?: string;
    'updatedByUserInfo'?: User;
    'versions'?: Array<AssetVersion>;
    'versionsNumber'?: number;
    'warning'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analyzeStatus",
            "baseName": "analyze_status",
            "type": "AssetElasticSchemaAnalyzeStatusEnum",
            "format": ""
        },
        {
            "name": "archiveStatus",
            "baseName": "archive_status",
            "type": "AssetElasticSchemaArchiveStatusEnum",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "commentsCount",
            "baseName": "comments_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "createdByUser",
            "baseName": "created_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdByUserInfo",
            "baseName": "created_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "customKeyframe",
            "baseName": "custom_keyframe",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "customPoster",
            "baseName": "custom_poster",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateDeleted",
            "baseName": "date_deleted",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateImported",
            "baseName": "date_imported",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateViewed",
            "baseName": "date_viewed",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedByUser",
            "baseName": "deleted_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "deletedByUserInfo",
            "baseName": "deleted_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "durationMilliseconds",
            "baseName": "duration_milliseconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalLink",
            "baseName": "external_link",
            "type": "string",
            "format": "url"
        },
        {
            "name": "favoured",
            "baseName": "favoured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "inCollections",
            "baseName": "in_collections",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isBlocked",
            "baseName": "is_blocked",
            "type": "boolean",
            "format": "bool"
        },
        {
            "name": "isOnline",
            "baseName": "is_online",
            "type": "boolean",
            "format": "bool"
        },
        {
            "name": "keyframes",
            "baseName": "keyframes",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "mediaType",
            "baseName": "media_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalAssetId",
            "baseName": "original_asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalSegmentId",
            "baseName": "original_segment_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalVersionId",
            "baseName": "original_version_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "proxies",
            "baseName": "proxies",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "relations",
            "baseName": "relations",
            "type": "Array<RelationElastic>",
            "format": ""
        },
        {
            "name": "siteName",
            "baseName": "site_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AssetElasticSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "timeEndMilliseconds",
            "baseName": "time_end_milliseconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timeStartMilliseconds",
            "baseName": "time_start_milliseconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AssetElasticSchemaTypeEnum",
            "format": ""
        },
        {
            "name": "updatedByUser",
            "baseName": "updated_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "updatedByUserInfo",
            "baseName": "updated_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<AssetVersion>",
            "format": ""
        },
        {
            "name": "versionsNumber",
            "baseName": "versions_number",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "warning",
            "baseName": "warning",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetElasticSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AssetElasticSchemaAnalyzeStatusEnum {
    NA = 'N/A',
    Requested = 'REQUESTED',
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    Done = 'DONE'
}
export enum AssetElasticSchemaArchiveStatusEnum {
    NotArchived = 'NOT_ARCHIVED',
    Archiving = 'ARCHIVING',
    FailedToArchive = 'FAILED_TO_ARCHIVE',
    Archived = 'ARCHIVED'
}
export enum AssetElasticSchemaStatusEnum {
    Active = 'ACTIVE',
    Deleted = 'DELETED'
}
export enum AssetElasticSchemaTypeEnum {
    Asset = 'ASSET',
    Sequence = 'SEQUENCE',
    NleProject = 'NLE_PROJECT',
    Placeholder = 'PLACEHOLDER',
    Custom = 'CUSTOM',
    Link = 'LINK',
    Subclip = 'SUBCLIP'
}

