/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EditAssetVersion } from '../models/EditAssetVersion';
import { HttpFile } from '../http/http';

export class AssetVersionsSchema {
    'assetId': string;
    'systemDomainId'?: string;
    'versions'?: Array<EditAssetVersion>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "systemDomainId",
            "baseName": "system_domain_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<EditAssetVersion>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetVersionsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

