/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AssetHistoryBulkSchema {
    'assetIds': Array<string>;
    'assetsJobsMap'?: any;
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'id'?: string;
    'jobId'?: string | null;
    'operationDescription'?: string | null;
    'operationType': AssetHistoryBulkSchemaOperationTypeEnum;
    'shareId'?: string | null;
    'shareUserId'?: string | null;
    'systemDomainId'?: string;
    'userId'?: string;
    'versionId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetIds",
            "baseName": "asset_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "assetsJobsMap",
            "baseName": "assets_jobs_map",
            "type": "any",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "operationDescription",
            "baseName": "operation_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "operationType",
            "baseName": "operation_type",
            "type": "AssetHistoryBulkSchemaOperationTypeEnum",
            "format": ""
        },
        {
            "name": "shareId",
            "baseName": "share_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "shareUserId",
            "baseName": "share_user_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "systemDomainId",
            "baseName": "system_domain_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return AssetHistoryBulkSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AssetHistoryBulkSchemaOperationTypeEnum {
    Export = 'EXPORT',
    Transcode = 'TRANSCODE',
    Analyze = 'ANALYZE',
    AddFormat = 'ADD_FORMAT',
    DeleteFormat = 'DELETE_FORMAT',
    RestoreFormat = 'RESTORE_FORMAT',
    DeleteFileset = 'DELETE_FILESET',
    DeleteFile = 'DELETE_FILE',
    RestoreFileset = 'RESTORE_FILESET',
    ModifyFileset = 'MODIFY_FILESET',
    Approve = 'APPROVE',
    Reject = 'REJECT',
    Download = 'DOWNLOAD',
    Metadata = 'METADATA',
    Custom = 'CUSTOM',
    Transcription = 'TRANSCRIPTION',
    VersionCreate = 'VERSION_CREATE',
    VersionDelete = 'VERSION_DELETE',
    VersionUpdate = 'VERSION_UPDATE',
    VersionPromote = 'VERSION_PROMOTE',
    Restore = 'RESTORE',
    RestoreFromGlacier = 'RESTORE_FROM_GLACIER',
    Archive = 'ARCHIVE',
    RestoreArchive = 'RESTORE_ARCHIVE',
    Delete = 'DELETE',
    Transfer = 'TRANSFER',
    UnlinkSubclip = 'UNLINK_SUBCLIP',
    FaceRecognition = 'FACE_RECOGNITION'
}

