/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class AssetBaseSchema {
    'analyzeStatus'?: AssetBaseSchemaAnalyzeStatusEnum;
    'archiveStatus'?: AssetBaseSchemaArchiveStatusEnum;
    'category'?: string | null;
    'createdByUser'?: string;
    'createdByUserInfo'?: User;
    'customKeyframe'?: string | null;
    'customPoster'?: string | null;
    'dateCreated'?: Date;
    'dateDeleted'?: Date;
    'dateImported'?: Date;
    'dateModified'?: Date;
    'dateViewed'?: Date;
    'deletedByUser'?: string;
    'deletedByUserInfo'?: User;
    'externalId'?: string | null;
    'externalLink'?: string | null;
    'favoured'?: boolean;
    'id'?: string;
    'isBlocked'?: boolean;
    'isOnline'?: boolean;
    'originalAssetId'?: string;
    'originalSegmentId'?: string;
    'originalVersionId'?: string;
    'siteName'?: string | null;
    'status'?: AssetBaseSchemaStatusEnum;
    'timeEndMilliseconds'?: number;
    'timeStartMilliseconds'?: number;
    'title': string;
    'type'?: AssetBaseSchemaTypeEnum;
    'updatedByUser'?: string;
    'updatedByUserInfo'?: User;
    'warning'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analyzeStatus",
            "baseName": "analyze_status",
            "type": "AssetBaseSchemaAnalyzeStatusEnum",
            "format": ""
        },
        {
            "name": "archiveStatus",
            "baseName": "archive_status",
            "type": "AssetBaseSchemaArchiveStatusEnum",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdByUser",
            "baseName": "created_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdByUserInfo",
            "baseName": "created_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "customKeyframe",
            "baseName": "custom_keyframe",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "customPoster",
            "baseName": "custom_poster",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateDeleted",
            "baseName": "date_deleted",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateImported",
            "baseName": "date_imported",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateViewed",
            "baseName": "date_viewed",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedByUser",
            "baseName": "deleted_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "deletedByUserInfo",
            "baseName": "deleted_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalLink",
            "baseName": "external_link",
            "type": "string",
            "format": "url"
        },
        {
            "name": "favoured",
            "baseName": "favoured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "isBlocked",
            "baseName": "is_blocked",
            "type": "boolean",
            "format": "bool"
        },
        {
            "name": "isOnline",
            "baseName": "is_online",
            "type": "boolean",
            "format": "bool"
        },
        {
            "name": "originalAssetId",
            "baseName": "original_asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalSegmentId",
            "baseName": "original_segment_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalVersionId",
            "baseName": "original_version_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "siteName",
            "baseName": "site_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AssetBaseSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "timeEndMilliseconds",
            "baseName": "time_end_milliseconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "timeStartMilliseconds",
            "baseName": "time_start_milliseconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AssetBaseSchemaTypeEnum",
            "format": ""
        },
        {
            "name": "updatedByUser",
            "baseName": "updated_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "updatedByUserInfo",
            "baseName": "updated_by_user_info",
            "type": "User",
            "format": ""
        },
        {
            "name": "warning",
            "baseName": "warning",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetBaseSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AssetBaseSchemaAnalyzeStatusEnum {
    NA = 'N/A',
    Requested = 'REQUESTED',
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    Done = 'DONE'
}
export enum AssetBaseSchemaArchiveStatusEnum {
    NotArchived = 'NOT_ARCHIVED',
    Archiving = 'ARCHIVING',
    FailedToArchive = 'FAILED_TO_ARCHIVE',
    Archived = 'ARCHIVED'
}
export enum AssetBaseSchemaStatusEnum {
    Active = 'ACTIVE',
    Deleted = 'DELETED'
}
export enum AssetBaseSchemaTypeEnum {
    Asset = 'ASSET',
    Sequence = 'SEQUENCE',
    NleProject = 'NLE_PROJECT',
    Placeholder = 'PLACEHOLDER',
    Custom = 'CUSTOM',
    Link = 'LINK',
    Subclip = 'SUBCLIP'
}

