/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetBatchExportItemSchema } from '../models/AssetBatchExportItemSchema';
import { HttpFile } from '../http/http';

export class AssetBatchExportSchema {
    'assets': Array<AssetBatchExportItemSchema>;
    'exportMetadata'?: boolean | null;
    'exportToAssetFolder'?: boolean | null;
    'metadataFormat'?: AssetBatchExportSchemaMetadataFormatEnum | null;
    'metadataView'?: string | null;
    'overwrite'?: boolean | null;
    'preferredOriginalStorageId'?: string | null;
    'transcodeProfileIds'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<AssetBatchExportItemSchema>",
            "format": ""
        },
        {
            "name": "exportMetadata",
            "baseName": "export_metadata",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "exportToAssetFolder",
            "baseName": "export_to_asset_folder",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "metadataFormat",
            "baseName": "metadata_format",
            "type": "AssetBatchExportSchemaMetadataFormatEnum",
            "format": ""
        },
        {
            "name": "metadataView",
            "baseName": "metadata_view",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "overwrite",
            "baseName": "overwrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "preferredOriginalStorageId",
            "baseName": "preferred_original_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "transcodeProfileIds",
            "baseName": "transcode_profile_ids",
            "type": "Array<string>",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return AssetBatchExportSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AssetBatchExportSchemaMetadataFormatEnum {
    Csv = 'CSV',
    Json = 'JSON',
    Xml = 'XML'
}

