/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BillingSettingsSchema {
    'autoRefillAmount'?: number | null;
    'enableAutoTopUp'?: boolean;
    'lowBalanceTrigger'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoRefillAmount",
            "baseName": "auto_refill_amount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "enableAutoTopUp",
            "baseName": "enable_auto_top_up",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lowBalanceTrigger",
            "baseName": "low_balance_trigger",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return BillingSettingsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

