/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BillingStatsSchema {
    'currentBalance'?: number;
    'invoiceEndOfMonth'?: boolean;
    'newBillingEnabled'?: boolean;
    'stripeId'?: boolean;
    'systemDomainStatus'?: BillingStatsSchemaSystemDomainStatusEnum | null;
    'systemDomainType': string;
    'systemDomainWarningMessage': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentBalance",
            "baseName": "current_balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "invoiceEndOfMonth",
            "baseName": "invoice_end_of_month",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "newBillingEnabled",
            "baseName": "new_billing_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stripeId",
            "baseName": "stripe_id",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "systemDomainStatus",
            "baseName": "system_domain_status",
            "type": "BillingStatsSchemaSystemDomainStatusEnum",
            "format": ""
        },
        {
            "name": "systemDomainType",
            "baseName": "system_domain_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "systemDomainWarningMessage",
            "baseName": "system_domain_warning_message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillingStatsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BillingStatsSchemaSystemDomainStatusEnum {
    Usd = 'USD',
    Eur = 'EUR'
}

