/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingCustomerShipping } from '../models/BillingCustomerShipping';
import { HttpFile } from '../http/http';

export class BillingCustomerSchema {
    'businessVatId'?: string;
    'email'?: string;
    'enableSubscription'?: boolean;
    'shipping': BillingCustomerShipping;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "businessVatId",
            "baseName": "business_vat_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "enableSubscription",
            "baseName": "enable_subscription",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shipping",
            "baseName": "shipping",
            "type": "BillingCustomerShipping",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BillingCustomerSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

