/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BulkCollectionTransferSchema {
    'collectionIds': Array<string>;
    'includeAssets': boolean;
    'includeCollections': boolean;
    'jobId': string;
    'keepCollectionStructure'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collectionIds",
            "baseName": "collection_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "includeAssets",
            "baseName": "include_assets",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includeCollections",
            "baseName": "include_collections",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "keepCollectionStructure",
            "baseName": "keep_collection_structure",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkCollectionTransferSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

