/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BulkACLSchema {
    'accessDenied'?: Array<string>;
    'accessGranted'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessDenied",
            "baseName": "access_denied",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "accessGranted",
            "baseName": "access_granted",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkACLSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

