/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BulkRemoveApprovalSchema {
    'objectIds': Array<string>;
    'objectType': BulkRemoveApprovalSchemaObjectTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectIds",
            "baseName": "object_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "BulkRemoveApprovalSchemaObjectTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkRemoveApprovalSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BulkRemoveApprovalSchemaObjectTypeEnum {
    Assets = 'assets',
    Collections = 'collections',
    SavedSearches = 'saved_searches'
}

