/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BulkFilesetRestoreSchema {
    'allowDuplicateTransfers'?: boolean;
    'deleteOnlyFromSourceFolder'?: boolean;
    'deleteOriginal'?: boolean;
    'destinationDirectoryPath'?: string | null;
    'destinationStorageId'?: string | null;
    'keepCollectionStructure'?: boolean;
    'objectIds': Array<string>;
    'objectType': BulkFilesetRestoreSchemaObjectTypeEnum;
    'preferredOriginalStorageId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowDuplicateTransfers",
            "baseName": "allow_duplicate_transfers",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteOnlyFromSourceFolder",
            "baseName": "delete_only_from_source_folder",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteOriginal",
            "baseName": "delete_original",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "destinationDirectoryPath",
            "baseName": "destination_directory_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationStorageId",
            "baseName": "destination_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "keepCollectionStructure",
            "baseName": "keep_collection_structure",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "objectIds",
            "baseName": "object_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "BulkFilesetRestoreSchemaObjectTypeEnum",
            "format": ""
        },
        {
            "name": "preferredOriginalStorageId",
            "baseName": "preferred_original_storage_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return BulkFilesetRestoreSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BulkFilesetRestoreSchemaObjectTypeEnum {
    Assets = 'assets',
    Collections = 'collections',
    SavedSearches = 'saved_searches'
}

