/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BulkDeleteSchema {
    /**
    * If set to `False`, will also delete entities of type `object_type` specified in `object_ids`.
    */
    'contentOnly'?: boolean;
    'objectIds': Array<string>;
    'objectType': BulkDeleteSchemaObjectTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contentOnly",
            "baseName": "content_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "objectIds",
            "baseName": "object_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "BulkDeleteSchemaObjectTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkDeleteSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BulkDeleteSchemaObjectTypeEnum {
    Assets = 'assets',
    Collections = 'collections',
    SavedSearches = 'saved_searches'
}

