/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BulkACLsObjectSchema } from '../models/BulkACLsObjectSchema';
import { HttpFile } from '../http/http';

export class CheckBulkACLsSchema {
    /**
    * The number of objects in the list is limited to a minimum of 0 and a maximum of 500
    */
    'objects': Array<BulkACLsObjectSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<BulkACLsObjectSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckBulkACLsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

