/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CollectionElasticSchema {
    'category'?: string | null;
    'createdByUser'?: string;
    'customKeyframe'?: string | null;
    'customOrderStatus'?: CollectionElasticSchemaCustomOrderStatusEnum;
    'customPoster'?: string | null;
    'dateCreated'?: Date;
    'dateDeleted'?: Date;
    'dateModified'?: Date;
    'deletedByUser'?: string;
    'externalId'?: string | null;
    'favoured'?: boolean;
    'id'?: string;
    'inCollections'?: Array<string>;
    'isRoot'?: boolean;
    'keyframeAssetIds'?: Array<string>;
    'keyframes'?: Array<any>;
    'metadata'?: any;
    'objectType'?: string;
    'parentId'?: string | null;
    'parents'?: Array<string>;
    'permissions'?: Array<string>;
    'position'?: number;
    'status'?: CollectionElasticSchemaStatusEnum;
    'storageId'?: string | null;
    'title': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdByUser",
            "baseName": "created_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "customKeyframe",
            "baseName": "custom_keyframe",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "customOrderStatus",
            "baseName": "custom_order_status",
            "type": "CollectionElasticSchemaCustomOrderStatusEnum",
            "format": ""
        },
        {
            "name": "customPoster",
            "baseName": "custom_poster",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateDeleted",
            "baseName": "date_deleted",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedByUser",
            "baseName": "deleted_by_user",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "favoured",
            "baseName": "favoured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "inCollections",
            "baseName": "in_collections",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "isRoot",
            "baseName": "is_root",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "keyframeAssetIds",
            "baseName": "keyframe_asset_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "keyframes",
            "baseName": "keyframes",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "parents",
            "baseName": "parents",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CollectionElasticSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionElasticSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CollectionElasticSchemaCustomOrderStatusEnum {
    Disabled = 'DISABLED',
    Enabling = 'ENABLING',
    Enabled = 'ENABLED'
}
export enum CollectionElasticSchemaStatusEnum {
    Active = 'ACTIVE',
    Hidden = 'HIDDEN',
    Deleted = 'DELETED'
}

