/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ComponentSchema {
    'id'?: string;
    /**
    * Sequence cannot have more than 10000. Excess values will be stripped
    */
    'metadata'?: { [key: string]: string; };
    'name': string;
    'type': ComponentSchemaTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ComponentSchemaTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComponentSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ComponentSchemaTypeEnum {
    Video = 'VIDEO',
    Audio = 'AUDIO',
    Image = 'IMAGE',
    Text = 'TEXT',
    Other = 'OTHER',
    NonMedia = 'NON_MEDIA',
    Exif = 'EXIF',
    Iptc = 'IPTC',
    Xmp = 'XMP',
    General = 'GENERAL'
}

