/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataValuesObjectId } from '../models/MetadataValuesObjectId';
import { HttpFile } from '../http/http';

export class CreateMetadataValuesBatchSchema {
    'assetId'?: string;
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'metadataValuesObjectIdMapping': Array<MetadataValuesObjectId>;
    'objectIds': Array<string>;
    'objectType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "metadataValuesObjectIdMapping",
            "baseName": "metadata_values_object_id_mapping",
            "type": "Array<MetadataValuesObjectId>",
            "format": ""
        },
        {
            "name": "objectIds",
            "baseName": "object_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateMetadataValuesBatchSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

