/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateShareACLsSchema {
    /**
    * The number of object_keys in the list is limited to a min of 0 and a maximum of 500
    */
    'objectKeys'?: Array<string>;
    'objectType'?: string;
    'permissions': Array<string>;
    'shareId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectKeys",
            "baseName": "object_keys",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "shareId",
            "baseName": "share_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return CreateShareACLsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

