/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreditsSchema {
    'country'?: string;
    'credits': number;
    'currency'?: string;
    'total'?: number;
    'vat'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "credits",
            "baseName": "credits",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "vat",
            "baseName": "vat",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return CreditsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

