/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CustomActionCallbackSchema {
    'assetIds'?: Array<string>;
    'collectionIds'?: Array<string>;
    'metadataValues'?: any;
    'metadataViewId'?: string | null;
    'savedSearchIds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetIds",
            "baseName": "asset_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "collectionIds",
            "baseName": "collection_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "metadataValues",
            "baseName": "metadata_values",
            "type": "any",
            "format": ""
        },
        {
            "name": "metadataViewId",
            "baseName": "metadata_view_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "savedSearchIds",
            "baseName": "saved_search_ids",
            "type": "Array<string>",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return CustomActionCallbackSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

