/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DefaultShareOptionsTypeSchema {
    'allowApprovingComments'?: boolean;
    'allowComments'?: boolean;
    'allowCustomActions'?: boolean;
    'allowDownload'?: boolean;
    'allowDownloadProxy'?: boolean;
    'allowSettingApproveStatus'?: boolean;
    'allowUpload'?: boolean;
    'allowViewTranscriptions'?: boolean;
    'allowViewVersions'?: boolean;
    'canChangeAllowApprovingComments'?: boolean;
    'canChangeAllowComments'?: boolean;
    'canChangeAllowCustomActions'?: boolean;
    'canChangeAllowDownload'?: boolean;
    'canChangeAllowDownloadProxy'?: boolean;
    'canChangeAllowSettingApproveStatus'?: boolean;
    'canChangeAllowUpload'?: boolean;
    'canChangeAllowViewTranscriptions'?: boolean;
    'canChangeAllowViewVersions'?: boolean;
    'canChangeSearchUsersFromShare'?: boolean;
    'canChangeShareExpirationTime'?: boolean;
    'requirePassword'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowApprovingComments",
            "baseName": "allow_approving_comments",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowComments",
            "baseName": "allow_comments",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowCustomActions",
            "baseName": "allow_custom_actions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowDownload",
            "baseName": "allow_download",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowDownloadProxy",
            "baseName": "allow_download_proxy",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowSettingApproveStatus",
            "baseName": "allow_setting_approve_status",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowUpload",
            "baseName": "allow_upload",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowViewTranscriptions",
            "baseName": "allow_view_transcriptions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowViewVersions",
            "baseName": "allow_view_versions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowApprovingComments",
            "baseName": "can_change_allow_approving_comments",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowComments",
            "baseName": "can_change_allow_comments",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowCustomActions",
            "baseName": "can_change_allow_custom_actions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowDownload",
            "baseName": "can_change_allow_download",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowDownloadProxy",
            "baseName": "can_change_allow_download_proxy",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowSettingApproveStatus",
            "baseName": "can_change_allow_setting_approve_status",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowUpload",
            "baseName": "can_change_allow_upload",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowViewTranscriptions",
            "baseName": "can_change_allow_view_transcriptions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeAllowViewVersions",
            "baseName": "can_change_allow_view_versions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeSearchUsersFromShare",
            "baseName": "can_change_search_users_from_share",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canChangeShareExpirationTime",
            "baseName": "can_change_share_expiration_time",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "requirePassword",
            "baseName": "require_password",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DefaultShareOptionsTypeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

