/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DrawingPoint } from '../models/DrawingPoint';
import { HttpFile } from '../http/http';

export class DrawingPrimitive {
    'color'?: string;
    'points'?: Array<DrawingPoint>;
    'text'?: string;
    'type': DrawingPrimitiveTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "Array<DrawingPoint>",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DrawingPrimitiveTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DrawingPrimitive.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DrawingPrimitiveTypeEnum {
    Line = 'LINE',
    Rectangle = 'RECTANGLE',
    Arrow = 'ARROW',
    Ellipse = 'ELLIPSE',
    Pencil = 'PENCIL',
    Text = 'TEXT'
}

