/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DrawingPrimitive } from '../models/DrawingPrimitive';
import { HttpFile } from '../http/http';

export class Drawing {
    'primitives'?: Array<DrawingPrimitive>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "primitives",
            "baseName": "primitives",
            "type": "Array<DrawingPrimitive>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Drawing.attributeTypeMap;
    }

    public constructor() {
    }
}

