/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EdgeTranscodeWorkerSchema {
    'id'?: string;
    'lastUpdateDate'?: Date;
    'status': EdgeTranscodeWorkerSchemaStatusEnum;
    'storageId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "lastUpdateDate",
            "baseName": "last_update_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EdgeTranscodeWorkerSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return EdgeTranscodeWorkerSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum EdgeTranscodeWorkerSchemaStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE'
}

