/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EdgeThumbnailJobFieldSchema } from '../models/EdgeThumbnailJobFieldSchema';
import { EdgeTranscodeInputSchema } from '../models/EdgeTranscodeInputSchema';
import { EdgeTranscodeJobFieldSchema } from '../models/EdgeTranscodeJobFieldSchema';
import { JobStep1 } from '../models/JobStep1';
import { HttpFile } from '../http/http';

export class EdgeTranscodeJobSchema {
    'assetId'?: string;
    'collectionId'?: string;
    'input': EdgeTranscodeInputSchema;
    'jobId'?: string;
    'jobSteps'?: Array<JobStep1>;
    'mediaInfo'?: string | null;
    'thumbnail'?: Array<EdgeThumbnailJobFieldSchema>;
    'transcode'?: Array<EdgeTranscodeJobFieldSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "EdgeTranscodeInputSchema",
            "format": ""
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobSteps",
            "baseName": "job_steps",
            "type": "Array<JobStep1>",
            "format": ""
        },
        {
            "name": "mediaInfo",
            "baseName": "media_info",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnail",
            "baseName": "thumbnail",
            "type": "Array<EdgeThumbnailJobFieldSchema>",
            "format": ""
        },
        {
            "name": "transcode",
            "baseName": "transcode",
            "type": "Array<EdgeTranscodeJobFieldSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EdgeTranscodeJobSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

