/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EditProxySettingsSchema {
    'audioBitrate'?: number;
    'audioCodec'?: string | null;
    'bitrate'?: number;
    'codec'?: string;
    'data'?: string;
    'deleteAfterUpload'?: boolean;
    'destinationPath'?: string | null;
    'excludePatterns'?: Array<string>;
    'height': number;
    'includePatterns'?: Array<string>;
    'local'?: boolean;
    'localDestinationPath'?: string | null;
    'minHeight'?: number;
    'minWidth'?: number;
    'priority'?: number | null;
    'storageId'?: string | null;
    'width': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "audioBitrate",
            "baseName": "audio_bitrate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "audioCodec",
            "baseName": "audio_codec",
            "type": "string",
            "format": ""
        },
        {
            "name": "bitrate",
            "baseName": "bitrate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "codec",
            "baseName": "codec",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "deleteAfterUpload",
            "baseName": "delete_after_upload",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "destinationPath",
            "baseName": "destination_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "localDestinationPath",
            "baseName": "local_destination_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "minHeight",
            "baseName": "min_height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minWidth",
            "baseName": "min_width",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return EditProxySettingsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

