/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EditReadyTranscoderSchema {
    'applyColorConversion'?: boolean;
    'bitrate'?: number;
    'createEditProxy'?: boolean;
    'deleteAfterUpload'?: boolean;
    'editProxyHeight'?: number;
    'editProxyLocalStoragePath'?: string;
    'editProxyUploadStorageId'?: string;
    'editProxyUploadStoragePath'?: string;
    'editProxyWidth'?: number;
    'editreadyPreset'?: string;
    'excludePatterns'?: Array<string>;
    'includePatterns'?: Array<string>;
    'local'?: boolean;
    'minHeight'?: number;
    'minWidth'?: number;
    'overwriteEditProxy'?: boolean;
    'videocodec'?: EditReadyTranscoderSchemaVideocodecEnum;
    'width': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applyColorConversion",
            "baseName": "apply_color_conversion",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "bitrate",
            "baseName": "bitrate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "createEditProxy",
            "baseName": "create_edit_proxy",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteAfterUpload",
            "baseName": "delete_after_upload",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "editProxyHeight",
            "baseName": "edit_proxy_height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "editProxyLocalStoragePath",
            "baseName": "edit_proxy_local_storage_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "editProxyUploadStorageId",
            "baseName": "edit_proxy_upload_storage_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "editProxyUploadStoragePath",
            "baseName": "edit_proxy_upload_storage_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "editProxyWidth",
            "baseName": "edit_proxy_width",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "editreadyPreset",
            "baseName": "editready_preset",
            "type": "string",
            "format": ""
        },
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "minHeight",
            "baseName": "min_height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minWidth",
            "baseName": "min_width",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "overwriteEditProxy",
            "baseName": "overwrite_edit_proxy",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "videocodec",
            "baseName": "videocodec",
            "type": "EditReadyTranscoderSchemaVideocodecEnum",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return EditReadyTranscoderSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum EditReadyTranscoderSchemaVideocodecEnum {
    _422Hq = 'Apple_ProRes_422_HQ',
    _422 = 'Apple_ProRes_422',
    _4444 = 'Apple_ProRes_4444',
    _422Lt = 'Apple_ProRes_422_LT',
    _422Proxy = 'Apple_ProRes_422_Proxy'
}

