/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EditProxySchema {
    'allowMxf'?: boolean | null;
    'directoryPath': string | null;
    'fileSuffix'?: string | null;
    'forceStorageId'?: boolean;
    'height': number;
    'ignoreTranscoderSettings'?: boolean;
    'name': string;
    'storageId': string;
    'versionId': string;
    'width': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowMxf",
            "baseName": "allow_mxf",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "directoryPath",
            "baseName": "directory_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSuffix",
            "baseName": "file_suffix",
            "type": "string",
            "format": ""
        },
        {
            "name": "forceStorageId",
            "baseName": "force_storage_id",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ignoreTranscoderSettings",
            "baseName": "ignore_transcoder_settings",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return EditProxySchema.attributeTypeMap;
    }

    public constructor() {
    }
}

