/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FacetBucketSchema } from '../models/FacetBucketSchema';
import { HttpFile } from '../http/http';

export class FacetSchema {
    'buckets'?: Array<FacetBucketSchema>;
    'docCountErrorUpperBound'?: number;
    'sumOtherDocCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<FacetBucketSchema>",
            "format": ""
        },
        {
            "name": "docCountErrorUpperBound",
            "baseName": "doc_count_error_upper_bound",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sumOtherDocCount",
            "baseName": "sum_other_doc_count",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return FacetSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

