/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FFmpegSettingsSchema {
    'audioBitrate'?: number;
    'bitrate'?: number;
    'data'?: string;
    'editProxyFolder'?: string | null;
    'excludePatterns'?: Array<string>;
    'hdrBrightness'?: number | null;
    'hdrContrast'?: number | null;
    'hdrGamma'?: number | null;
    'hdrSaturation'?: number | null;
    'hdrTonemapDesat'?: number | null;
    'hdrTonemapPeak'?: number | null;
    'includePatterns'?: Array<string>;
    'local'?: boolean;
    'overlayCoordinates'?: string | null;
    'overlayUrl'?: string | null;
    'priority'?: number | null;
    'scalingMethod'?: FFmpegSettingsSchemaScalingMethodEnum;
    'width'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "audioBitrate",
            "baseName": "audio_bitrate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "bitrate",
            "baseName": "bitrate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "editProxyFolder",
            "baseName": "edit_proxy_folder",
            "type": "string",
            "format": ""
        },
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "hdrBrightness",
            "baseName": "hdr_brightness",
            "type": "number",
            "format": ""
        },
        {
            "name": "hdrContrast",
            "baseName": "hdr_contrast",
            "type": "number",
            "format": ""
        },
        {
            "name": "hdrGamma",
            "baseName": "hdr_gamma",
            "type": "number",
            "format": ""
        },
        {
            "name": "hdrSaturation",
            "baseName": "hdr_saturation",
            "type": "number",
            "format": ""
        },
        {
            "name": "hdrTonemapDesat",
            "baseName": "hdr_tonemap_desat",
            "type": "number",
            "format": ""
        },
        {
            "name": "hdrTonemapPeak",
            "baseName": "hdr_tonemap_peak",
            "type": "number",
            "format": ""
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "overlayCoordinates",
            "baseName": "overlay_coordinates",
            "type": "string",
            "format": ""
        },
        {
            "name": "overlayUrl",
            "baseName": "overlay_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "scalingMethod",
            "baseName": "scaling_method",
            "type": "FFmpegSettingsSchemaScalingMethodEnum",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return FFmpegSettingsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum FFmpegSettingsSchemaScalingMethodEnum {
    FastBilinear = 'fast_bilinear',
    Bilinear = 'bilinear',
    Bicubic = 'bicubic',
    Experimental = 'experimental',
    Neighbor = 'neighbor',
    Area = 'area',
    Bicublin = 'bicublin',
    Gauss = 'gauss',
    Sinc = 'sinc',
    Lanczos = 'lanczos',
    Spline = 'spline',
    AccurateRnd = 'accurate_rnd',
    FullChromaInt = 'full_chroma_int',
    FullChromaInp = 'full_chroma_inp',
    Bitexact = 'bitexact'
}

