/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FormatArchiveSchema {
    'deleteOriginal'?: boolean;
    'destinationDirectoryPath'?: string;
    'destinationFileSetName'?: string;
    'destinationStorageId'?: string;
    'destinationStorageMethod'?: string;
    'formatId'?: string;
    'originalFileSetId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deleteOriginal",
            "baseName": "delete_original",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "destinationDirectoryPath",
            "baseName": "destination_directory_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationFileSetName",
            "baseName": "destination_file_set_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationStorageId",
            "baseName": "destination_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "destinationStorageMethod",
            "baseName": "destination_storage_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "formatId",
            "baseName": "format_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalFileSetId",
            "baseName": "original_file_set_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return FormatArchiveSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

