/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IdentityProviderSchema {
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'id'?: string;
    'publicId'?: string;
    'samlSettings'?: any | null;
    'settings': any | null;
    'type': IdentityProviderSchemaTypeEnum;
    'verboseLogging'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "publicId",
            "baseName": "public_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "samlSettings",
            "baseName": "saml_settings",
            "type": "any",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "any",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IdentityProviderSchemaTypeEnum",
            "format": ""
        },
        {
            "name": "verboseLogging",
            "baseName": "verbose_logging",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IdentityProviderSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum IdentityProviderSchemaTypeEnum {
    OneloginCom = 'onelogin.com',
    Auth0Com = 'auth0.com',
    OktaCom = 'okta.com',
    Generic = 'GENERIC'
}

