/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ImageMagickSettingsSchema {
    'data'?: string;
    'excludePatterns'?: Array<string>;
    'height'?: number;
    'includePatterns'?: Array<string>;
    'local'?: boolean;
    'overlayCoordinates'?: string | null;
    'overlayUrl'?: string | null;
    'priority'?: number | null;
    'width'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "overlayCoordinates",
            "baseName": "overlay_coordinates",
            "type": "string",
            "format": ""
        },
        {
            "name": "overlayUrl",
            "baseName": "overlay_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ImageMagickSettingsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

