/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobChildProgressSchema {
    'progressProcessed'?: number;
    'progressTotal'?: number;
    'status'?: JobChildProgressSchemaStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "progressProcessed",
            "baseName": "progress_processed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "progressTotal",
            "baseName": "progress_total",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JobChildProgressSchemaStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobChildProgressSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum JobChildProgressSchemaStatusEnum {
    Ready = 'READY',
    Started = 'STARTED',
    Finished = 'FINISHED',
    FinishedWithWarning = 'FINISHED_WITH_WARNING',
    Failed = 'FAILED',
    Waiting = 'WAITING',
    AbortPending = 'ABORT_PENDING',
    Aborted = 'ABORTED',
    Skipped = 'SKIPPED',
    Paused = 'PAUSED'
}

