/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobsStateSchema1 {
    'action': JobsStateSchema1ActionEnum;
    'jobIds': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "JobsStateSchema1ActionEnum",
            "format": ""
        },
        {
            "name": "jobIds",
            "baseName": "job_ids",
            "type": "Array<string>",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return JobsStateSchema1.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum JobsStateSchema1ActionEnum {
    Pause = 'PAUSE',
    Resume = 'RESUME',
    Abort = 'ABORT',
    Restart = 'RESTART'
}

