/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Sort } from '../models/Sort';
import { HttpFile } from '../http/http';

export class JobsWidgetOption {
    'columns'?: Array<string>;
    'filters'?: any;
    'limit'?: number;
    'sort'?: Array<Sort>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "columns",
            "baseName": "columns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "any",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<Sort>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobsWidgetOption.attributeTypeMap;
    }

    public constructor() {
    }
}

