/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InputSchema } from '../models/InputSchema';
import { JobStep1 } from '../models/JobStep1';
import { ThumbnailJob } from '../models/ThumbnailJob';
import { TranscodeJob } from '../models/TranscodeJob';
import { Transcoders } from '../models/Transcoders';
import { HttpFile } from '../http/http';

export class JobSchema1 {
    'amazonRekognition'?: boolean;
    'analysisData'?: any;
    'analysisQueryDefaultServiceAccount'?: boolean;
    'analyzedBefore'?: boolean;
    'assetId'?: string;
    'assetLink'?: string;
    'collectionId'?: string;
    'createTranscription'?: boolean;
    'forceTranscoder'?: string;
    'googleCloudVideoIntelligence'?: boolean;
    'input'?: InputSchema;
    'jobId'?: string;
    'jobSteps'?: Array<JobStep1>;
    'language'?: string | null;
    'mediaInfo'?: string | null;
    'overwrite'?: boolean;
    'priority'?: number;
    'speakers'?: number | null;
    'thumbnail'?: Array<ThumbnailJob>;
    'transcode'?: Array<TranscodeJob>;
    'validTranscoders'?: Array<Transcoders>;
    'versionId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amazonRekognition",
            "baseName": "amazon_rekognition",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "analysisData",
            "baseName": "analysis_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "analysisQueryDefaultServiceAccount",
            "baseName": "analysis_query_default_service_account",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "analyzedBefore",
            "baseName": "analyzed_before",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "assetLink",
            "baseName": "asset_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createTranscription",
            "baseName": "create_transcription",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "forceTranscoder",
            "baseName": "force_transcoder",
            "type": "string",
            "format": ""
        },
        {
            "name": "googleCloudVideoIntelligence",
            "baseName": "google_cloud_video_intelligence",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "InputSchema",
            "format": ""
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobSteps",
            "baseName": "job_steps",
            "type": "Array<JobStep1>",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediaInfo",
            "baseName": "media_info",
            "type": "string",
            "format": ""
        },
        {
            "name": "overwrite",
            "baseName": "overwrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "speakers",
            "baseName": "speakers",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "thumbnail",
            "baseName": "thumbnail",
            "type": "Array<ThumbnailJob>",
            "format": ""
        },
        {
            "name": "transcode",
            "baseName": "transcode",
            "type": "Array<TranscodeJob>",
            "format": ""
        },
        {
            "name": "validTranscoders",
            "baseName": "valid_transcoders",
            "type": "Array<Transcoders>",
            "format": ""
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobSchema1.attributeTypeMap;
    }

    public constructor() {
    }
}

