/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobStepUpdateBulkSchema {
    'dateUpdated'?: Date;
    'errorMessage'?: string | null;
    'id': string;
    'label': string;
    'message'?: string | null;
    'status': JobStepUpdateBulkSchemaStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateUpdated",
            "baseName": "date_updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JobStepUpdateBulkSchemaStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobStepUpdateBulkSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum JobStepUpdateBulkSchemaStatusEnum {
    InProgress = 'IN_PROGRESS',
    Waiting = 'WAITING',
    Failed = 'FAILED',
    Done = 'DONE',
    Skipped = 'SKIPPED'
}

