/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EndpointSchema } from '../models/EndpointSchema';
import { HttpFile } from '../http/http';

export class LocalTranscodeInputSchema {
    'assetId': string;
    'checksum'?: string | null;
    'closedCaptions'?: boolean;
    'collectionId'?: string | null;
    'componentIds'?: Array<string>;
    'directoryPath': string;
    'endpoint': EndpointSchema;
    'engine'?: string;
    'fileId': string;
    'fileSetId': string;
    'filename': string;
    'formatId': string;
    'language'?: string;
    'originalName'?: string;
    'proxyId'?: string | null;
    'size': number;
    'storageId': string;
    'updateProxyMediainfo'?: boolean | null;
    'versionId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "checksum",
            "baseName": "checksum",
            "type": "string",
            "format": ""
        },
        {
            "name": "closedCaptions",
            "baseName": "closed_captions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "componentIds",
            "baseName": "component_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "directoryPath",
            "baseName": "directory_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "EndpointSchema",
            "format": ""
        },
        {
            "name": "engine",
            "baseName": "engine",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileId",
            "baseName": "file_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSetId",
            "baseName": "file_set_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "formatId",
            "baseName": "format_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalName",
            "baseName": "original_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "proxyId",
            "baseName": "proxy_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "updateProxyMediainfo",
            "baseName": "update_proxy_mediainfo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LocalTranscodeInputSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

