/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LogsRecipientReadSchema {
    'id'?: string;
    'method': LogsRecipientReadSchemaMethodEnum;
    'name': string;
    'settings': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "LogsRecipientReadSchemaMethodEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LogsRecipientReadSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum LogsRecipientReadSchemaMethodEnum {
    Google = 'GOOGLE',
    Amazon = 'AMAZON'
}

