/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MetadataFieldValueSchema {
    'dateCreated'?: Date;
    'fieldValues'?: Array<any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fieldValues",
            "baseName": "field_values",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetadataFieldValueSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

