/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataFieldSchema } from '../models/MetadataFieldSchema';
import { HttpFile } from '../http/http';

export class MetadataViewSchema {
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'description'?: string | null;
    'id'?: string;
    'name': string;
    'viewFields': Array<MetadataFieldSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "viewFields",
            "baseName": "view_fields",
            "type": "Array<MetadataFieldSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetadataViewSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

