/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MetadataFieldMappingUpdateSchema {
    'fieldType'?: string;
    'mappedFieldName': string;
    'name'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldType",
            "baseName": "field_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mappedFieldName",
            "baseName": "mapped_field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetadataFieldMappingUpdateSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

