/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MoveAssetResourceSchema {
    'destinationAssetId': string;
    'destinationVersionId': string;
    'excludeFormatIds'?: Array<string> | null;
    'sourceVersionId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "destinationAssetId",
            "baseName": "destination_asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "destinationVersionId",
            "baseName": "destination_version_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "excludeFormatIds",
            "baseName": "exclude_format_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "sourceVersionId",
            "baseName": "source_version_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return MoveAssetResourceSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

