/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MultipartUploadCleanupSchema {
    'abortUpload'?: boolean;
    'partsGroupNumber'?: number | null;
    'partsNumber'?: number;
    'temporary'?: boolean;
    'uploadId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "abortUpload",
            "baseName": "abort_upload",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "partsGroupNumber",
            "baseName": "parts_group_number",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "partsNumber",
            "baseName": "parts_number",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "temporary",
            "baseName": "temporary",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "uploadId",
            "baseName": "upload_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultipartUploadCleanupSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

