/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MultipartUploadSchema {
    'partsGroup'?: number | null;
    'partsRange': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "partsGroup",
            "baseName": "parts_group",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "partsRange",
            "baseName": "parts_range",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultipartUploadSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

