/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MultiPartS3UrlPartSchema {
    /**
    * base64-encoded md5 digest
    */
    'checksum'?: string | null;
    'partNumber'?: number;
    'url'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checksum",
            "baseName": "checksum",
            "type": "string",
            "format": ""
        },
        {
            "name": "partNumber",
            "baseName": "part_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultiPartS3UrlPartSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

