/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MultiPartURLsSchema {
    'abortUrl'?: string;
    'completeUrl'?: string;
    'listPartsUrl'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "abortUrl",
            "baseName": "abort_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "completeUrl",
            "baseName": "complete_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "listPartsUrl",
            "baseName": "list_parts_url",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultiPartURLsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

