/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PriceSchema {
    'currency': PriceSchemaCurrencyEnum;
    'name': string;
    'prices': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "PriceSchemaCurrencyEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "prices",
            "baseName": "prices",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PriceSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PriceSchemaCurrencyEnum {
    Eur = 'EUR',
    Usd = 'USD'
}

