/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResolutionType } from '../models/ResolutionType';
import { HttpFile } from '../http/http';

export class ProxySchema {
    'assetId'?: string;
    'audioBitrate'?: number;
    'bitRate'?: number;
    'codec'?: string;
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'filename'?: string;
    'format'?: string;
    'frameRate'?: string | null;
    'id'?: string;
    'isDropFrame'?: boolean | null;
    'isPublic'?: boolean;
    'multipartUploadUrl'?: string;
    'name'?: string;
    'resolution'?: ResolutionType;
    'rotation'?: number | null;
    'size'?: number | null;
    'startTimeCode'?: string | null;
    'status'?: ProxySchemaStatusEnum;
    'storageId': string;
    'storageMethod'?: string;
    'uploadCredentials'?: any;
    'uploadMethod'?: string;
    'uploadUrl'?: string;
    'url'?: string;
    'versionId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "audioBitrate",
            "baseName": "audio_bitrate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "bitRate",
            "baseName": "bit_rate",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "codec",
            "baseName": "codec",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string",
            "format": ""
        },
        {
            "name": "frameRate",
            "baseName": "frame_rate",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "isDropFrame",
            "baseName": "is_drop_frame",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPublic",
            "baseName": "is_public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "multipartUploadUrl",
            "baseName": "multipart_upload_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "ResolutionType",
            "format": ""
        },
        {
            "name": "rotation",
            "baseName": "rotation",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "startTimeCode",
            "baseName": "start_time_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ProxySchemaStatusEnum",
            "format": ""
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "storageMethod",
            "baseName": "storage_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "uploadCredentials",
            "baseName": "upload_credentials",
            "type": "any",
            "format": ""
        },
        {
            "name": "uploadMethod",
            "baseName": "upload_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "uploadUrl",
            "baseName": "upload_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return ProxySchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ProxySchemaStatusEnum {
    Open = 'OPEN',
    Growing = 'GROWING',
    Awaited = 'AWAITED',
    Closed = 'CLOSED',
    Failed = 'FAILED',
    Archived = 'ARCHIVED',
    Missing = 'MISSING',
    Rediscovered = 'REDISCOVERED',
    Deleted = 'DELETED'
}

