/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RedlineSchema {
    'editProxyLocalStoragePath'?: string;
    'editProxyUploadStorageId'?: string;
    'editProxyUploadStoragePath'?: string;
    'excludePatterns'?: Array<string>;
    'format'?: RedlineSchemaFormatEnum;
    'includePatterns'?: Array<string>;
    'keepRedlineProxy'?: boolean;
    'local'?: boolean;
    'openclDeviceIndexes'?: Array<string>;
    'priority'?: number | null;
    'qtCodec'?: RedlineSchemaQtCodecEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "editProxyLocalStoragePath",
            "baseName": "edit_proxy_local_storage_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "editProxyUploadStorageId",
            "baseName": "edit_proxy_upload_storage_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "editProxyUploadStoragePath",
            "baseName": "edit_proxy_upload_storage_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "RedlineSchemaFormatEnum",
            "format": ""
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keepRedlineProxy",
            "baseName": "keep_redline_proxy",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "openclDeviceIndexes",
            "baseName": "opencl_device_indexes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "qtCodec",
            "baseName": "qt_codec",
            "type": "RedlineSchemaQtCodecEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedlineSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RedlineSchemaFormatEnum {
    QtTranscode = 'QT transcode',
    AppleProRes = 'Apple ProRes',
    Empty = ''
}
export enum RedlineSchemaQtCodecEnum {
    H264 = 'H264',
    H263 = 'H263',
    Avid1080PDnxHd368Bit = 'AVID_1080P_DNxHD_36_8-bit',
    Avid1080PDnxHd1151208Bit = 'AVID_1080P_DNxHD_115/120_8-bit',
    Avid1080PDnxHd1751858Bit = 'AVID_1080P_DNxHD_175/185_8-bit',
    Avid1080PDnxHd17518510Bit = 'AVID_1080P_DNxHD_175/185_10-bit',
    Avid720PDnxHd60758Bit = 'AVID_720P_DNxHD_60/75_8-bit',
    Avid720PDnxHd901108Bit = 'AVID_720P_DNxHD_90/110_8-bit',
    Avid720PDnxHd9011010Bit = 'AVID_720P_DNxHD_90/110_10-bit',
    Avid720PDnxHd1201458Bit = 'AVID_720P_DNxHD_120/145_8-bit',
    Avid720PDnxHd1852208Bit = 'AVID_720P_DNxHD_185/220_8-bit',
    Avid720PDnxHd18522010Bit = 'AVID_720P_DNxHD_185/220_10-bit',
    AppleProRes422Hq = 'Apple_ProRes_422_HQ',
    AppleProRes422 = 'Apple_ProRes_422',
    AppleProRes4444 = 'Apple_ProRes_4444',
    AppleProRes422Lt = 'Apple_ProRes_422_LT',
    AppleProRes422Proxy = 'Apple_ProRes_422_Proxy',
    Empty = ''
}

