/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReferralCodeSchema {
    'code': string;
    'doNotDelete'?: boolean | null;
    'manageSystemDomainId'?: string | null;
    'ordwayCustomerId'?: string | null;
    'salesForceId'?: string | null;
    'validTo': Date;
    'value': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "doNotDelete",
            "baseName": "do_not_delete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manageSystemDomainId",
            "baseName": "manage_system_domain_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "ordwayCustomerId",
            "baseName": "ordway_customer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesForceId",
            "baseName": "sales_force_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "validTo",
            "baseName": "valid_to",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReferralCodeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

