/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReindexSegmentsSchema {
    'ignoreComments'?: boolean;
    'realms'?: Array<string> | null;
    'segmentIds': Array<string>;
    'syncToAnotherDc'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ignoreComments",
            "baseName": "ignore_comments",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "realms",
            "baseName": "realms",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "segmentIds",
            "baseName": "segment_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "syncToAnotherDc",
            "baseName": "sync_to_another_dc",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReindexSegmentsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

