/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RelationTypeSchema {
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'description'?: string | null;
    'destinationLabel': string;
    'isDirectional'?: boolean;
    'isSystem'?: boolean;
    'name': string;
    'sourceLabel': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationLabel",
            "baseName": "destination_label",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDirectional",
            "baseName": "is_directional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSystem",
            "baseName": "is_system",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceLabel",
            "baseName": "source_label",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RelationTypeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

