/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SearchSuggestSchema {
    'docTypes'?: Array<string>;
    'fieldName': string;
    'metadataViewId'?: string;
    'query': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "docTypes",
            "baseName": "doc_types",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadataViewId",
            "baseName": "metadata_view_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchSuggestSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

