/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ShareUserSchema {
    'accessCount'?: number;
    'email': string;
    'firstName'?: string;
    'id'?: string;
    'internalUserId'?: string;
    'lastAccessDate'?: Date;
    'lastName'?: string;
    'objectId'?: string;
    'objectType'?: string;
    'password'?: string;
    'photo'?: string;
    'photoBig'?: string;
    'photoSmall'?: string;
    'shareId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessCount",
            "baseName": "access_count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "internalUserId",
            "baseName": "internal_user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastAccessDate",
            "baseName": "last_access_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string",
            "format": ""
        },
        {
            "name": "photoBig",
            "baseName": "photo_big",
            "type": "string",
            "format": ""
        },
        {
            "name": "photoSmall",
            "baseName": "photo_small",
            "type": "string",
            "format": ""
        },
        {
            "name": "shareId",
            "baseName": "share_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShareUserSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

