/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StorageFilesDeleteBulkSchema {
    /**
    * The number of object_ids in the list is limited to a minimum of 0 and a maximum of 500
    */
    'objectIds': Array<string>;
    'objectType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "objectIds",
            "baseName": "object_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StorageFilesDeleteBulkSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

