/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StorageReadSchema {
    '_default'?: boolean;
    'description'?: string | null;
    'id'?: string;
    'isgVersion'?: string;
    'lastScanned'?: Date | null;
    'method': StorageReadSchemaMethodEnum;
    'name': string;
    'purpose': StorageReadSchemaPurposeEnum;
    'scannerStatus'?: string | null;
    'settings': any;
    'status'?: StorageReadSchemaStatusEnum;
    'statusMessage'?: string | null;
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "isgVersion",
            "baseName": "isg_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastScanned",
            "baseName": "last_scanned",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "StorageReadSchemaMethodEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "purpose",
            "baseName": "purpose",
            "type": "StorageReadSchemaPurposeEnum",
            "format": ""
        },
        {
            "name": "scannerStatus",
            "baseName": "scanner_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "any",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StorageReadSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "statusMessage",
            "baseName": "status_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StorageReadSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum StorageReadSchemaMethodEnum {
    File = 'FILE',
    Http = 'HTTP',
    Ftp = 'FTP',
    Sftp = 'SFTP',
    S3 = 'S3',
    B2 = 'B2',
    Gcs = 'GCS',
    Portal = 'PORTAL',
    Custom = 'CUSTOM',
    Azure = 'AZURE'
}
export enum StorageReadSchemaPurposeEnum {
    Keyframes = 'KEYFRAMES',
    Files = 'FILES',
    Proxies = 'PROXIES',
    Exports = 'EXPORTS',
    Archive = 'ARCHIVE',
    Faces = 'FACES'
}
export enum StorageReadSchemaStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE',
    Failing = 'FAILING'
}

