/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StorageUsageSchema {
    'bucketName': string;
    'bytesStored'?: number;
    'date'?: Date;
    'id'?: string;
    'storageType': StorageUsageSchemaStorageTypeEnum;
    'systemDomainId'?: string;
    'systemName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bucketName",
            "baseName": "bucket_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "bytesStored",
            "baseName": "bytes_stored",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "storageType",
            "baseName": "storage_type",
            "type": "StorageUsageSchemaStorageTypeEnum",
            "format": ""
        },
        {
            "name": "systemDomainId",
            "baseName": "system_domain_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "systemName",
            "baseName": "system_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StorageUsageSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum StorageUsageSchemaStorageTypeEnum {
    File = 'FILE',
    Http = 'HTTP',
    Ftp = 'FTP',
    Sftp = 'SFTP',
    S3 = 'S3',
    Omms = 'OMMS',
    Gcs = 'GCS',
    B2 = 'B2',
    Azure = 'AZURE',
    Transfer = 'TRANSFER'
}

