/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StorageScanSchema {
    'files'?: Array<string> | null;
    /**
    * Will force scanning even if the scan is already active if any of `paths` or `files` are specified.
    */
    'ignoreAlreadyActive'?: boolean;
    'paths'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "ignoreAlreadyActive",
            "baseName": "ignore_already_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "paths",
            "baseName": "paths",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StorageScanSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

