/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SystemDomainSchema {
    'baseUrl': string;
    'customTerms'?: boolean;
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'deactivateDate'?: Date;
    'description'?: string;
    'discountPercent'?: number;
    'doNotChargeEdgeTranscoder'?: boolean;
    'doNotChargeRemoteProxies'?: boolean;
    'doNotChargeShield'?: boolean;
    'freezeDate'?: Date;
    'id'?: string;
    'invoiceEndOfMonth'?: boolean;
    'isTemplate'?: boolean;
    'marketplaceCustomerId'?: string;
    'marketplaceEntitlementId'?: string;
    'name': string;
    'ordwayCustomerId'?: string;
    'ordwaySubscriptionId'?: string;
    'priceList'?: string;
    'referralCode'?: string;
    'salesForceId'?: string;
    'status'?: SystemDomainSchemaStatusEnum;
    'stripeId'?: string;
    'type'?: SystemDomainSchemaTypeEnum;
    'warningMessage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "baseUrl",
            "baseName": "base_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "customTerms",
            "baseName": "custom_terms",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deactivateDate",
            "baseName": "deactivate_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "discountPercent",
            "baseName": "discount_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "doNotChargeEdgeTranscoder",
            "baseName": "do_not_charge_edge_transcoder",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "doNotChargeRemoteProxies",
            "baseName": "do_not_charge_remote_proxies",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "doNotChargeShield",
            "baseName": "do_not_charge_shield",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "freezeDate",
            "baseName": "freeze_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "invoiceEndOfMonth",
            "baseName": "invoice_end_of_month",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isTemplate",
            "baseName": "is_template",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "marketplaceCustomerId",
            "baseName": "marketplace_customer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "marketplaceEntitlementId",
            "baseName": "marketplace_entitlement_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "ordwayCustomerId",
            "baseName": "ordway_customer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "ordwaySubscriptionId",
            "baseName": "ordway_subscription_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "priceList",
            "baseName": "price_list",
            "type": "string",
            "format": ""
        },
        {
            "name": "referralCode",
            "baseName": "referral_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "salesForceId",
            "baseName": "sales_force_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SystemDomainSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "stripeId",
            "baseName": "stripe_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SystemDomainSchemaTypeEnum",
            "format": ""
        },
        {
            "name": "warningMessage",
            "baseName": "warning_message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemDomainSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SystemDomainSchemaStatusEnum {
    Active = 'ACTIVE',
    Warning = 'WARNING',
    Frozen = 'FROZEN',
    Deactivated = 'DEACTIVATED'
}
export enum SystemDomainSchemaTypeEnum {
    Trial = 'TRIAL',
    Customer = 'CUSTOMER',
    Partner = 'PARTNER',
    Internal = 'INTERNAL'
}

