/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllowedIPSchema } from '../models/AllowedIPSchema';
import { DefaultShareOptionsTypeSchema } from '../models/DefaultShareOptionsTypeSchema';
import { FacetFieldSchema } from '../models/FacetFieldSchema';
import { JobsDashboardSchema } from '../models/JobsDashboardSchema';
import { PasswordChecksTypeSchema } from '../models/PasswordChecksTypeSchema';
import { SearchDisplayFieldSchema } from '../models/SearchDisplayFieldSchema';
import { HttpFile } from '../http/http';

export class SystemSettingPublicSchema {
    'aclTemplateId'?: string | null;
    'allowedIps'?: Array<AllowedIPSchema>;
    'assetDefaultSections'?: Array<string>;
    'clientIp'?: string;
    'collectionsGetParentAcls'?: boolean | null;
    'corsHosts'?: Array<string>;
    'customTerms'?: boolean;
    'dateFormat'?: string | null;
    'datetimeFormat'?: string | null;
    'defaultShareOptions'?: DefaultShareOptionsTypeSchema | null;
    'defaultUploadStorageId'?: string | null;
    /**
    * Grace period that indicate how long objects will live in recycle bin. Unit: hours
    */
    'deleteGracePeriod'?: number | null;
    'enableShield'?: boolean | null;
    'externalShare'?: boolean | null;
    'facetFields'?: Array<FacetFieldSchema>;
    'filtersDefaultMetadataViewId'?: string | null;
    'hideFavourites'?: boolean | null;
    'homePage'?: string | null;
    'imagePropertiesMetadataField'?: string | null;
    'jobsDashboard'?: JobsDashboardSchema | null;
    'locationsMetadataField'?: string | null;
    /**
    * Forbid regular users to edit or delete mapped collections.
    */
    'lockMappedCollections'?: boolean | null;
    'logoStorageId'?: string | null;
    'logoUrl'?: string;
    'logosMetadataField'?: string | null;
    'maxBrowseUsers'?: number | null;
    'maxPowerUsers'?: number | null;
    'maxStandardUsers'?: number | null;
    'maxStorageBytes'?: number | null;
    'maxTrafficBytes'?: number | null;
    'passwordChecks'?: PasswordChecksTypeSchema | null;
    'requiredMetadataViews'?: Array<string>;
    'safeSearchesMetadataField'?: string | null;
    'samlRequireGroups'?: boolean | null;
    'searchDefaultSections'?: Array<string>;
    'searchDisplayFields'?: Array<SearchDisplayFieldSchema>;
    'searchInTranscriptions'?: boolean | null;
    'searchResultsAssetMetadataViewId'?: string | null;
    'searchResultsCollectionMetadataViewId'?: string | null;
    'searchUsersFromShare'?: boolean | null;
    /**
    * Default share expiration time that indicate how long share will be valid. Unit: days
    */
    'shareExpirationTime'?: number | null;
    'supportAccess'?: boolean | null;
    'systemDomainId'?: string;
    'systemDomainName'?: string;
    'tagsMetadataField'?: string | null;
    'textsMetadataField'?: string | null;
    'updateSamlPrimaryGroupOnLogin'?: boolean | null;
    'useAssetNameOnDownload'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aclTemplateId",
            "baseName": "acl_template_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "allowedIps",
            "baseName": "allowed_ips",
            "type": "Array<AllowedIPSchema>",
            "format": ""
        },
        {
            "name": "assetDefaultSections",
            "baseName": "asset_default_sections",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "clientIp",
            "baseName": "client_ip",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionsGetParentAcls",
            "baseName": "collections_get_parent_acls",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "corsHosts",
            "baseName": "cors_hosts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "customTerms",
            "baseName": "custom_terms",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dateFormat",
            "baseName": "date_format",
            "type": "string",
            "format": ""
        },
        {
            "name": "datetimeFormat",
            "baseName": "datetime_format",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultShareOptions",
            "baseName": "default_share_options",
            "type": "DefaultShareOptionsTypeSchema",
            "format": ""
        },
        {
            "name": "defaultUploadStorageId",
            "baseName": "default_upload_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "deleteGracePeriod",
            "baseName": "delete_grace_period",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "enableShield",
            "baseName": "enable_shield",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "externalShare",
            "baseName": "external_share",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "facetFields",
            "baseName": "facet_fields",
            "type": "Array<FacetFieldSchema>",
            "format": ""
        },
        {
            "name": "filtersDefaultMetadataViewId",
            "baseName": "filters_default_metadata_view_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "hideFavourites",
            "baseName": "hide_favourites",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "homePage",
            "baseName": "home_page",
            "type": "string",
            "format": ""
        },
        {
            "name": "imagePropertiesMetadataField",
            "baseName": "image_properties_metadata_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobsDashboard",
            "baseName": "jobs_dashboard",
            "type": "JobsDashboardSchema",
            "format": ""
        },
        {
            "name": "locationsMetadataField",
            "baseName": "locations_metadata_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "lockMappedCollections",
            "baseName": "lock_mapped_collections",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "logoStorageId",
            "baseName": "logo_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "logoUrl",
            "baseName": "logo_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "logosMetadataField",
            "baseName": "logos_metadata_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxBrowseUsers",
            "baseName": "max_browse_users",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxPowerUsers",
            "baseName": "max_power_users",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxStandardUsers",
            "baseName": "max_standard_users",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxStorageBytes",
            "baseName": "max_storage_bytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxTrafficBytes",
            "baseName": "max_traffic_bytes",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "passwordChecks",
            "baseName": "password_checks",
            "type": "PasswordChecksTypeSchema",
            "format": ""
        },
        {
            "name": "requiredMetadataViews",
            "baseName": "required_metadata_views",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "safeSearchesMetadataField",
            "baseName": "safe_searches_metadata_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "samlRequireGroups",
            "baseName": "saml_require_groups",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "searchDefaultSections",
            "baseName": "search_default_sections",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "searchDisplayFields",
            "baseName": "search_display_fields",
            "type": "Array<SearchDisplayFieldSchema>",
            "format": ""
        },
        {
            "name": "searchInTranscriptions",
            "baseName": "search_in_transcriptions",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "searchResultsAssetMetadataViewId",
            "baseName": "search_results_asset_metadata_view_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "searchResultsCollectionMetadataViewId",
            "baseName": "search_results_collection_metadata_view_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "searchUsersFromShare",
            "baseName": "search_users_from_share",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shareExpirationTime",
            "baseName": "share_expiration_time",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "supportAccess",
            "baseName": "support_access",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "systemDomainId",
            "baseName": "system_domain_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "systemDomainName",
            "baseName": "system_domain_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tagsMetadataField",
            "baseName": "tags_metadata_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "textsMetadataField",
            "baseName": "texts_metadata_field",
            "type": "string",
            "format": ""
        },
        {
            "name": "updateSamlPrimaryGroupOnLogin",
            "baseName": "update_saml_primary_group_on_login",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useAssetNameOnDownload",
            "baseName": "use_asset_name_on_download",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemSettingPublicSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

