/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SystemDomainFromTemplateSchema {
    'adminEmail': string;
    'adminFirstName'?: string;
    'adminLastName'?: string;
    'adminPassword'?: string;
    'baseUrl'?: string;
    'customTerms'?: boolean;
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'description'?: string;
    'id'?: string;
    'name': string;
    'type'?: SystemDomainFromTemplateSchemaTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "adminEmail",
            "baseName": "admin_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "adminFirstName",
            "baseName": "admin_first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "adminLastName",
            "baseName": "admin_last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "adminPassword",
            "baseName": "admin_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseUrl",
            "baseName": "base_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "customTerms",
            "baseName": "custom_terms",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SystemDomainFromTemplateSchemaTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemDomainFromTemplateSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SystemDomainFromTemplateSchemaTypeEnum {
    Trial = 'TRIAL',
    Customer = 'CUSTOMER',
    Partner = 'PARTNER',
    Internal = 'INTERNAL'
}

