/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TelestreamCloudSchema {
    'accessKey': string;
    'apiHost'?: string;
    'apiPort'?: number;
    'excludePatterns'?: Array<string>;
    'factoryId': string;
    'includePatterns'?: Array<string>;
    'keyframesProfileId': string;
    'local'?: boolean;
    'priority'?: number | null;
    'proxyProfileId': string;
    'secretKey': string;
    'storageId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessKey",
            "baseName": "access_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiHost",
            "baseName": "api_host",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiPort",
            "baseName": "api_port",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "factoryId",
            "baseName": "factory_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "keyframesProfileId",
            "baseName": "keyframes_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "proxyProfileId",
            "baseName": "proxy_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretKey",
            "baseName": "secret_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TelestreamCloudSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

