/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeBaseTypeSchema } from '../models/TimeBaseTypeSchema';
import { HttpFile } from '../http/http';

export class TimeCodeTypeSchema {
    'framesNumber'?: number;
    'isDropFrame'?: boolean;
    'timeBase'?: TimeBaseTypeSchema;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "framesNumber",
            "baseName": "frames_number",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isDropFrame",
            "baseName": "is_drop_frame",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "timeBase",
            "baseName": "time_base",
            "type": "TimeBaseTypeSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimeCodeTypeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

