/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TimeBaseTypeSchema {
    'denominator'?: number;
    'numerator'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "denominator",
            "baseName": "denominator",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "numerator",
            "baseName": "numerator",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return TimeBaseTypeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

