/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TranscodeQueueRecordSchema {
    'bytesParams'?: any | null;
    'dateCreated'?: string;
    'dateUpdated'?: string;
    'id'?: string;
    'jobId'?: string | null;
    'mediaInfo'?: string | null;
    'objectId'?: string | null;
    'objectType'?: string | null;
    'params'?: string | null;
    'priority'?: number | null;
    'retryCount'?: number | null;
    'spec'?: string | null;
    'status'?: string | null;
    'systemDomainId'?: string | null;
    'systemName'?: string;
    'type'?: string | null;
    'userId'?: string | null;
    'versionId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bytesParams",
            "baseName": "bytes_params",
            "type": "any",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateUpdated",
            "baseName": "date_updated",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "mediaInfo",
            "baseName": "media_info",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "objectType",
            "baseName": "object_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": ""
        },
        {
            "name": "retryCount",
            "baseName": "retry_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "spec",
            "baseName": "spec",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "systemDomainId",
            "baseName": "system_domain_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "systemName",
            "baseName": "system_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "versionId",
            "baseName": "version_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return TranscodeQueueRecordSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

