/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TranscodeRequestSchema {
    'priority'?: number | null;
    'setAsCustomKeyframe'?: boolean | null;
    'updateProxyMediainfo'?: boolean;
    'useStorageTranscodeIgnorePattern'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "setAsCustomKeyframe",
            "baseName": "set_as_custom_keyframe",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updateProxyMediainfo",
            "baseName": "update_proxy_mediainfo",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useStorageTranscodeIgnorePattern",
            "baseName": "use_storage_transcode_ignore_pattern",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TranscodeRequestSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

