/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransferFromStorageSchema {
    'assetId'?: string;
    'assetPaths'?: Array<string>;
    'collectionStorageId'?: string;
    'componentIds'?: Array<string>;
    'deleteLocalFileSetAfterUpload'?: boolean;
    'deleteOnlyFromSourceFolder'?: boolean;
    'deleteSourceFileSetAfterDownload'?: boolean;
    'destinationDirectoryPath'?: string;
    'destinationFileSetName'?: string;
    'destinationFilename'?: string;
    'destinationStorageId'?: string;
    'destinationStorageMethod'?: string;
    'formatId'?: string;
    'id'?: string;
    'jobId'?: string;
    'jobSteps'?: any;
    'originalFileSetId'?: string;
    'originalStorageId'?: string;
    'originalUrl'?: string;
    'parentJobId'?: string;
    'temporaryFileSetSource'?: boolean;
    'transferType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "assetPaths",
            "baseName": "asset_paths",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "collectionStorageId",
            "baseName": "collection_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "componentIds",
            "baseName": "component_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "deleteLocalFileSetAfterUpload",
            "baseName": "delete_local_file_set_after_upload",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteOnlyFromSourceFolder",
            "baseName": "delete_only_from_source_folder",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteSourceFileSetAfterDownload",
            "baseName": "delete_source_file_set_after_download",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "destinationDirectoryPath",
            "baseName": "destination_directory_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationFileSetName",
            "baseName": "destination_file_set_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationFilename",
            "baseName": "destination_filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationStorageId",
            "baseName": "destination_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "destinationStorageMethod",
            "baseName": "destination_storage_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "formatId",
            "baseName": "format_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "jobSteps",
            "baseName": "job_steps",
            "type": "any",
            "format": ""
        },
        {
            "name": "originalFileSetId",
            "baseName": "original_file_set_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalStorageId",
            "baseName": "original_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalUrl",
            "baseName": "original_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "parentJobId",
            "baseName": "parent_job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "temporaryFileSetSource",
            "baseName": "temporary_file_set_source",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "transferType",
            "baseName": "transfer_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferFromStorageSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

