/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TranscribeSchema {
    'engine'?: string | null;
    'force'?: boolean;
    'language'?: string | null;
    'profileId'?: string;
    'speakers'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "engine",
            "baseName": "engine",
            "type": "string",
            "format": ""
        },
        {
            "name": "force",
            "baseName": "force",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        },
        {
            "name": "profileId",
            "baseName": "profile_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "speakers",
            "baseName": "speakers",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return TranscribeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

