/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TranscodeValidateMediaInfoSchema {
    'filename'?: string;
    'mediaInfo': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediaInfo",
            "baseName": "media_info",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TranscodeValidateMediaInfoSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

