/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TransferCloudSchema {
    'assetId'?: string;
    'assetPaths'?: Array<string>;
    'celeryTaskId'?: string;
    'collectionStorageId'?: string;
    'componentIds'?: Array<string>;
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'deleteOnlyFromSourceFolder'?: boolean;
    'deleteOriginal'?: boolean;
    'destinationDirectoryPath'?: string;
    'destinationFilename'?: string;
    'destinationStorageId'?: string;
    'id'?: string;
    'jobId'?: string;
    'jobSteps'?: any;
    'originalFileSetId'?: string;
    'originalStorageId'?: string;
    'originalUrl'?: string;
    'parentJobId'?: string;
    'priority'?: number;
    'status'?: TransferCloudSchemaStatusEnum;
    'success'?: string;
    'transferType'?: string;
    'userId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "assetPaths",
            "baseName": "asset_paths",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "celeryTaskId",
            "baseName": "celery_task_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "collectionStorageId",
            "baseName": "collection_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "componentIds",
            "baseName": "component_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "dateCreated",
            "baseName": "date_created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateModified",
            "baseName": "date_modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deleteOnlyFromSourceFolder",
            "baseName": "delete_only_from_source_folder",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteOriginal",
            "baseName": "delete_original",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "destinationDirectoryPath",
            "baseName": "destination_directory_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationFilename",
            "baseName": "destination_filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationStorageId",
            "baseName": "destination_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "jobSteps",
            "baseName": "job_steps",
            "type": "any",
            "format": ""
        },
        {
            "name": "originalFileSetId",
            "baseName": "original_file_set_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalStorageId",
            "baseName": "original_storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "originalUrl",
            "baseName": "original_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "parentJobId",
            "baseName": "parent_job_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TransferCloudSchemaStatusEnum",
            "format": ""
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferType",
            "baseName": "transfer_type",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return TransferCloudSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TransferCloudSchemaStatusEnum {
    Q = 'Q',
    U = 'U',
    E = 'E',
    D = 'D'
}

