/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TranscoderByStorageReadSchema {
    'id'?: string;
    'name'?: string;
    'settings'?: any;
    'storageId'?: string;
    'type'?: TranscoderByStorageReadSchemaTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "any",
            "format": ""
        },
        {
            "name": "storageId",
            "baseName": "storage_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TranscoderByStorageReadSchemaTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TranscoderByStorageReadSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TranscoderByStorageReadSchemaTypeEnum {
    Vantage = 'VANTAGE',
    Ffmpeg = 'FFMPEG',
    EditProxy = 'EDIT_PROXY',
    Imagemagick = 'IMAGEMAGICK',
    EncodingCom = 'ENCODING_COM',
    Zencoder = 'ZENCODER',
    TelestreamCloud = 'TELESTREAM_CLOUD',
    ElementalMediaconvert = 'ELEMENTAL_MEDIACONVERT',
    ElementalServer = 'ELEMENTAL_SERVER',
    Redline = 'REDLINE',
    IconikEdgeTranscoder = 'ICONIK_EDGE_TRANSCODER',
    WatchFolderVideo = 'WATCH_FOLDER_VIDEO',
    Editready = 'EDITREADY'
}

