/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserSchema {
    'email'?: string;
    'firstName'?: string;
    'id'?: string;
    'lastName'?: string;
    'photo'?: string;
    'photoBig'?: string;
    'photoSmall'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string",
            "format": ""
        },
        {
            "name": "photoBig",
            "baseName": "photo_big",
            "type": "string",
            "format": ""
        },
        {
            "name": "photoSmall",
            "baseName": "photo_small",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

