/**
 * Iconik
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VantageSettingsSchema {
    'excludePatterns'?: Array<string>;
    'host': string;
    'includePatterns'?: Array<string>;
    'local'?: boolean;
    'port': number;
    'priority'?: number | null;
    'shareName': string;
    'tempProxyFolder': string;
    'workflowId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "excludePatterns",
            "baseName": "exclude_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "host",
            "baseName": "host",
            "type": "string",
            "format": ""
        },
        {
            "name": "includePatterns",
            "baseName": "include_patterns",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "shareName",
            "baseName": "share_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tempProxyFolder",
            "baseName": "temp_proxy_folder",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowId",
            "baseName": "workflow_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VantageSettingsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}

