name: Publish

on:
  workflow_run:
    workflows: ["Generate SDK"]
    types:
      - completed

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies and build
        run: |
          cd typescript-client
          npm install
          npm run build

      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
